---
- name: "Create new location for ssh keys"
  file: path=/etc/ssh/keys state=directory 
  sudo: yes
- name: "Copy ssh keys from template"
  template: src=flask_authorized_keys dest=/etc/ssh/keys/flask_authorized_keys mode=0600
  sudo: yes
  
- name: "Copy root keys"
  template: src=root_authorized_keys dest=/etc/ssh/keys/root_authorized_keys mode=0600
  sudo: yes

- name: "Copy sshd_config"
  template: src=sshd_config dest=/etc/ssh
  notify: restart sshd


